GET http://localhost:3333/questions/list-by-type-question/MULTIPLE_CHOICE

###
GET http://localhost:3333/questions/list-by-type-question/ESSAY

###
GET http://localhost:3000/tweets/634586dbcef12dae83f3bde3

###
GET http://localhost:3333/educators

###
POST http://localhost:3333/educators/enroll
Content-Type: application/json

{
    "name": "Maick Outro Teste",
    "course": "Cálculo discreto"
}

###
PUT http://localhost:3333/educators/update/710df79f-87cc-4ec1-8af5-f69f7402f33a
Content-Type: application/json

{
    "name": "Maick Souza",
    "course": "NodeJs"
}