###
GET http://localhost:3333/questions/list-by-type-question/MULTIPLE_CHOICE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Njk5ODc0MDUsImV4cCI6MTY2OTk5NDYwNSwic3ViIjoiNzcyNWNlOTMtMDAyOC00YzMzLWJlZGQtMzI1ZWFkNjRmNzhkIn0.oxtaU-KzJYX-vEt4shKahXlqx7v6f9ynZL21TFSpvyM
###
GET http://localhost:3333/questions/list-by-type-question/ESSAY
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Njk5ODc0MDUsImV4cCI6MTY2OTk5NDYwNSwic3ViIjoiNzcyNWNlOTMtMDAyOC00YzMzLWJlZGQtMzI1ZWFkNjRmNzhkIn0.oxtaU-KzJYX-vEt4shKahXlqx7v6f9ynZL21TFSpvyM

###
GET http://localhost:3333/questions/list-by-subject/português
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzAzMTkwOTUsImV4cCI6MTY3MDMyNjI5NSwic3ViIjoiNzcyNWNlOTMtMDAyOC00YzMzLWJlZGQtMzI1ZWFkNjRmNzhkIn0.LYK2-XyfsmpStcV7tLQy3wkvo4dMNRKhqxo4iVm6V6M


###
GET http://localhost:3000/tweets/634586dbcef12dae83f3bde3

###
GET http://localhost:3333/educators
Content-Type: application/json


###
POST http://localhost:3333/educators/enroll
Content-Type: application/json

{
    "name": "Maick Outro Teste",
    "email": "maick@teste.com",
    "password": "123456",
    "course": "Cálculo discreto"
}

###
POST http://localhost:3333/educators/auth
Content-Type: application/json

{
    "email": "maick@teste.com",
    "password": "123456"
}

###
POST http://localhost:3333/questions/create
Content-Type: application/json

{
    "type_question": "",
    "subject": "",
    "description": "",
    "essay_answer": "",
    "choice_01": "",
    "choice_02": "",
    "choice_03": "",
    "choice_04": "",
    "choice_05": "",
    "correct": ""
}

###
PUT http://localhost:3333/educators/update/710df79f-87cc-4ec1-8af5-f69f7402f33a
Content-Type: application/json

{
    "name": "Maick Souza",
    "course": "NodeJs"
}

###
DELETE http://localhost:3333/educators/delete/cd8ad39e-c44a-420a-8396-e8b4e021d683

